### ISSUE TITLE
Unable to build on Mac OS X 10.11

### ISSUE THREAD

**Issue by farazfazli** [r-lyeh-archived/bundler#6]
When attempting to build on Mac OS X 10.11 following the instructions in the README, the following error is produced:

```
bundler.cc:14:10: fatal error: 'wire/wire.hpp' file not found
#include <wire/wire.hpp>
         ^
1 error generated.
```

**Comment by r-lyeh** [comment]
Did you clone with `git clone https://github.com/r-lyeh/bundler --recursive` ?
